# Generated by Django 3.2.4 on 2021-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=1500)),
                ('category', models.CharField(default='General', max_length=25)),
                ('author', models.CharField(default='Admin', max_length=25)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
