# Generated by Django 3.2.4 on 2021-09-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='pub_date',
        ),
    ]
