# Generated by Django 3.2.4 on 2021-09-21 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_remove_content_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
