# Generated by Django 3.2.4 on 2021-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_content_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
    ]
